server:
  port: 8080
  servlet:
    context-path: /linking

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/linking?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    useSSL: false


  resources:
    static-locations: classpath:/static/

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html
      cache: false
      encoding: UTF-8

  jpa:
    database: mysql
    show-sql: true
    hibernate:
        ddl-auto: update
        naming:
            implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: false


  security:
    user:
      name: user
      password: user







